# Project Configuration
project_id = "ohwhvdeilpiiaadbkkla"

# Auth Configuration
[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Database Configuration
[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

# API Configuration
[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

# Studio Configuration
[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Storage Configuration
[storage]
enabled = true
file_size_limit = "50MiB"

# Realtime Configuration
[realtime]
enabled = true
ip_version = "IPv4"

# Inbucket Configuration
[inbucket]
enabled = true
port = 54324

# Analytics Configuration
[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

# JWT configuration should be in .env file
# JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
# ANON_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
# SERVICE_ROLE_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...