project_id = "ohwhvdeilpiiaadbkkla"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000",
  "http://localhost:3000",
  "https://127.0.0.1:3000",
  "http://127.0.0.1:3000"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true